Import('env', 'LIB_DIR')
import os.path

env = env.Clone()

source_files = Split("""ColorRGB.cc
		Lights.cc
		Loader_Obj.cc
		Material.cc
		Object3d.cc
		OpenGL.cc
		OpenGL_state.cc
		PngWriter.cc
		Rasterizer.cc
		SDL_Display.cc
		VertexBuffer.cc
		VertexOps.cc
		GL/gl.cc
		""")

env.Library(target = os.path.join(LIB_DIR, 'ggl'), source = source_files)
